export const SEND_MKR_TO_PROXY_SUCCESS = 'proxy/SEND_MKR_TO_PROXY_SUCCESS';
export const WITHDRAW_MKR_SUCCESS = 'proxy/WITHDRAW_MKR_SUCCESS';
export const MKR_APPROVE_SUCCESS = 'proxy/MKR_APPROVE_SUCCESS';
export const IOU_APPROVE_SUCCESS = 'proxy/IOU_APPROVE_SUCCESS';
